#ifndef __JOHN_RSA_CORE_H__
#define __JOHN_RSA_CORE_H__

#define JOHN_SHARED_RSA_KEY_SIZE (4096 / 8)
#define JOHN_SHARED_RSA_KEY_BUFFER_SIZE 4096
#define JOHN_SHARED_DATA_MAX 500

#define JOHN_SPECIFIC_RSA_KEY_SIZE (1024 / 8)
#define JOHN_SPECIFIC_RSA_KEY_BUFFER_SIZE 1024
#define JOHN_SPECIFIC_DATA_MAX 116

#endif /* __JOHN_RSA_CORE_H__ */
